server:
  port: 9001
  tomcat:
    connection-timeout: 5s
    threads:
      min-spare: 10
      max: 100
polar:
  greeting: Welcome to the local book catalog!
spring:
  profiles:
    active: test-data
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888