server:
  port: 9001
  tomcat:
    connection-timeout: 5s
    threads:
      min-spare: 10
      max: 100
spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888